### ISSUE TITLE
is there a way to get profit from fish filets?

### ISSUE THREAD

**Issue by ViralDoom** [Lambda11/Fish-Deleter#1]
Hi! At the moment im using Fish Filets to make Fish Crates V to sell to Merchants NPCs. But, is there a way to sell the fishes instead of dismatle them? there are good spots where merchants are close to fishing áreas. I know is a lower profit vs Fish Crates V, but still a good profit.

Let me know if i can help :)

BTW, ur code is awesome, thx for this!

**Comment by Owyn** [comment]
I think the other fish manager had a selling feature https://github.com/SoliaRdi/auto-fishing , while let-me-fish wasn't intended for profit making at all, just for auto fishing and getting fillets to fill the marker to crafted stuff from it

**Comment by ViralDoom** [comment]
got it! thanks anyway ^^

p.s. why delete the filets then?
